--- #Demo Install Composer
- hosts: mydemogrp
  become: yes
  gather_facts: yes
  user: ansible1
  connection: ssh
  tasks:
    - name: Installation install software-properties-common
      apt: name=software-properties-common
    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"
    - name: install php
      apt: name=php7.4 state=present
    - name: install composer
      composer:
        command: install
        working_dir: /var/www/
